debug: True
token: 305643264:AAGwALg3QDiH2OrNzqehgoPdeXwpIqY416c
logging:
  level: DEBUG
  # filename: 'app.log'
  # filemode: 'w'
  # level: ERROR
db:
  args: ['sqlite:///datebase.db']
  kwargs: {'connect_args':{'check_same_thread': False}}